complexity:
  TooManyFunctions:
    thresholdInFiles: 15
  LongParameterList:
    functionThreshold: 15
    ignoreDefaultParameters: true


naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true