name: Build
on:
  pull_request:
  push:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the app
        uses: gradle/gradle-build-action@v2
        # can we use spotless to run detekt ?
        #      - name: Check spotless
        #        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

      - name: Update api.key from Secrets
        env:
          api.key: ${{ secrets.API_KEY }}
        run: echo api.key="$API_KEY" > ./local.properties

      - name: Check lint
        run: ./gradlew lintDebug

      #      - name: Build all build type and flavor permutations
      #        run: ./gradlew assemble

      - name: Run local tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: reports/TEST-result.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports
