name: Build
on:
  pull_request:
  push:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      api.key: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build the app
        uses: gradle/gradle-build-action@v2
      # can we use spotless to run detekt ?
      #      - name: Check spotless
      #        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check lint
        run: ./gradlew lintDebug

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble

      - name: Run local tests
        run: ./gradlew testDebug

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports
