name: Build
on:
  pull_request:
  push:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build the app
        uses: gradle/gradle-build-action@v2
      - name: Run local tests
        run: ./gradlew testDemoDebug testProdDebug
      - name: Upload build reports
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: build-reports
            path: app/build/reports
